### ISSUE TITLE
Delay cancelled message is shown when using tp/warp command

### ISSUE THREAD

**Issue by i9hdkill** [DarkBlade12/SimpleAlias#3]
Actions:
    ExecuteCommand:
      Type: COMMAND
      Priority: 0
      Translate_Color_Codes: false
      Command: tp 182 4 891
Delay:
    Enabled: true
    Cancel_On_Move: true
    Duration: 3

After the action was succesfully executed (player was moved away), the delay cancelled message is shown.

**Comment by xtechgamer735** [comment]
Only just seen this! But are you still having this issue?

**Comment by i9hdkill** [comment]
Yes, this is still an issue

**Comment by xtechgamer735** [comment]
Please could you send me the full file so I can test it?

**Comment by i9hdkill** [comment]
Sure,
https://www.dropbox.com/s/by20lnn60op6uta/SimpleAlias.rar?dl=0
This alias ( /vip) peerforms a teleport. But even when the teleport is finished, the canceled message is shown.

**Comment by xtechgamer735** [comment]
This is a strange one. It seems you are doing better than I am - since I don't get a delay or message at all. The command executes straight away! It would seem this is a bug with the plugin. Your best bet might be to see if your TP plugin has built in delays. Its probably best if @DarkBlade12 takes a look at this.

**Comment by i9hdkill** [comment]
you are probably opped. You can set "need permission X" to false if you don't have a permission plugin installed.
Players don't have the /tp perms, so a delay from the teleport plugin is not possible, as the simplealias option grants permisions for /tp (So the tp plugin would skip the internal delay anyway)

**Comment by xtechgamer735** [comment]
I did think that myself at the time although I have denied myself the permission and de-opped myself which did not work. The only thing I can think it to try re making it from in game?
